# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{activemerchant-payway}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Lambie", "Dan Galipo", "Dirk Kelly"]
  s.date = %q{2010-12-01}
  s.description = %q{ActiveMerchant PayWay Plugin}
  s.email = %q{dk@dirkkelly.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "activemerchant-payway.gemspec",
    "config/credentials.txt",
    "config/payway.pem",
    "init.rb",
    "lib/active_merchant/billing/gateways/pay_way.rb",
    "lib/activemerchant-payway.rb",
    "test/remote/gateways/remote_pay_way_test.rb",
    "test/test_helper.rb",
    "test/unit/gateways/pay_way_test.rb"
  ]
  s.homepage = %q{http://github.com/thefrontiergroup/activemerchant-payway}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ActiveMerchant PayWay Plugin}
  s.test_files = [
    "test/remote/gateways/remote_pay_way_test.rb",
    "test/test_helper.rb",
    "test/unit/gateways/pay_way_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activemerchant>, [">= 1.9.1"])
    else
      s.add_dependency(%q<activemerchant>, [">= 1.9.1"])
    end
  else
    s.add_dependency(%q<activemerchant>, [">= 1.9.1"])
  end
end

